post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: geany
remote:
  command: rsync
  settings: -av --delete
  source: _site/
  destination: username@servername:/var/www/websitename/
